#!/bin/bash
# Prepare the simulator output for analysis with R.
# By Theresa Enghardt and Philipp S. Tiesel
#
# Usage:
#		./prepare_output.sh <directory> <outputfile>
#			<directory> -	Directory of the .csv files generated by the simulator
#			<outputfile> -	File name for the output .csv file that will later be used by R

# Combine all input files to one output file
# Substitute the first '+' in the output file by a comma, separating the website and the crawler run from each other
find $1 -type f -name \*.csv -print0 | parallel -0 --max-procs=4 --progress --max-args=255 cat > "$2"
